module.exports = {
  appName: 'js13k2017',
  sourceFiles: [
    "js/engine/functions.js",
    "js/engine/input.js",
    "js/engine/camera.js",
    "js/engine/scene.js",
    "js/engine/group.js",
    "js/engine/sprite.js",
    "js/engine/collisions.js",
    "js/engine/svg.js",
    "js/engine/animator.js",
    "js/engine/sound.js",
    "js/engine/rect.js",
    "js/engine/point.js",
    "js/engine/astar.js",
    "js/engine/text.js",
    "js/engine/init.js",

    "js/constants.js",
    "js/scenes/menu.js",
    "js/scenes/game.js",
    "js/level.js",
    "js/player.js",
    "js/wall.js",
    "js/zombie.js",
    "js/spawner.js",
    "js/ai_director.js",
    "js/items.js",
    "js/game.js",
  ]
}
