module.exports = {
  appName: 'pandemia',
  sourceFiles: [
    "js/engine/functions.js",
    "js/engine/input.js",
    "js/engine/camera.js",
    "js/engine/scene.js",
    "js/engine/group.js",
    "js/engine/sprite.js",
    "js/engine/collisions.js",
    "js/engine/animator.js",
    "js/engine/jsfxr.js",
    "js/engine/sound.js",
    "js/engine/rect.js",
    "js/engine/point.js",
    "js/engine/astar.js",
    "js/engine/text.js",
    "js/engine/init.js",

    "js/constants.js",
    "js/scenes/menu.js",
    "js/scenes/game.js",
    "js/level.js",
    "js/player.js",
    "js/npc.js",
    "js/wall.js",
    "js/zombie.js",
    "js/spawner.js",
    "js/items.js",
    "js/hud.js",
    //"js/perlin_noise.js",
    "js/effects.js",
    "js/bullet.js",
    "js/zones.js",
    "js/game.js",
  ]
}
